# Generated by Django 3.1.5 on 2021-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='category',
            field=models.CharField(choices=[('enfant', 'enfant'), ('adult', 'adult')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='festival',
            name='places',
            field=models.CharField(choices=[(1, 1), (2, 2)], default='', max_length=15),
        ),
    ]
