# Generated by Django 3.1.5 on 2021-01-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='places',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='', max_length=15),
        ),
    ]
