# Generated by Django 3.1.5 on 2021-01-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210130_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('enfant', 'enfant'), ('adult', 'adult'), ('etudiant', 'etudiant')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='places',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=0, max_length=15),
        ),
    ]
